added new keyboard layout and enabled the use of tilt sensor for certain keys
Catrobat/ScratchToCatrobat pull request #179
Opened 2020-05-31 14:20 UTC by sandra0521

2020-06-10 16:01 UTC, AntiDog requested changes
as discussed: change show hide to visibility, use new formula element generation instead of separate functions

2020-06-18 12:00 UTC, AntiDog approved these changes

2020-07-23 15:02 UTC, aurarius1 approved these changes

2020-07-23 15:06 UTC, merged

2020-07-23 15:07 UTC, wslany commented
Thanks!