STCC-270 merged _key* functions [TL, SS]
Catrobat/ScratchToCatrobat pull request #189
Opened 2020-07-19 15:17 UTC by aurarius1

*Please enter a short description of your pull request and add a reference to the Jira ticket.*

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ x] Include the name of the Jira ticket in the PR’s title
- [ x] Include a summary of the changes plus the relevant context
- [ x] Choose the proper base branch (*develop*)
- [ x] Confirm that the changes follow the project’s coding guidelines
- [ x] Verify that the changes generate no compiler warnings
- [ x] Perform a self-review of the changes
- [ x] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ x] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines) (Replace occurences of CATROBAT or CAT with STCC)
- [ x] Stick to the project’s gitflow workflow
- [ x] Verify that your changes do not have any conflicts with the base branch
- [ ] Post a message in the *#stcc* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2020-07-23 07:23 UTC, sandra0521 requested changes

2020-07-23 07:23 UTC, sandra0521 commented on src/scratchtocatrobat/converter/converter.py
> +# def _key_filename_for(key):
Please remove commented code

2020-07-23 07:26 UTC, sandra0521 commented
This PR will need merge conflicts resolved after #179 is merged into develop.

2020-07-24 13:08 UTC, sandra0521 approved these changes

2020-07-31 14:33 UTC, lildeaf approved these changes

2020-07-31 14:33 UTC, merged